-- 014: prices.metadata column (issue adapters#58 / core#219). MySQL mirror of
-- postgres/migrations/015_price_metadata.up.sql.
--
-- Background. core v0.3.0's pricing.Price carries integrator-defined metadata
-- (Metadata() map[string]string, surfaced as PriceSnapshot.Metadata). The
-- adapter previously dropped it: Save never wrote it and reads returned a
-- price with empty metadata. This adds a metadata column mirroring the one
-- products already has, so the price repository can round-trip it.
--
-- MySQL 8 requires an expression default for JSON columns, hence
-- (JSON_OBJECT()) rather than a literal '{}'. Existing rows (and prices built
-- without WithMetadata) read back as empty metadata; pricing.FromSnapshot
-- tolerates a nil/empty map.
--
-- Forward-only runner (no .down files); a mid-file failure is caught by the
-- 'pending' status marker.
ALTER TABLE prices ADD COLUMN metadata JSON NOT NULL DEFAULT (JSON_OBJECT());
